CREATE TABLE IF NOT EXISTS public.bus_bookings
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    bus_id bigint,
    booked_by text COLLATE pg_catalog."default" NOT NULL,
    booked_by_email text COLLATE pg_catalog."default",
    purpose character varying(255) COLLATE pg_catalog."default",
    destination character varying(255) COLLATE pg_catalog."default",
    start_date date NOT NULL,
    end_date date NOT NULL,
    booking_period character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'FULL_DAY'::character varying,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    passenger_count integer,
    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'PENDING'::character varying,
    remarks text COLLATE pg_catalog."default",
    approved_by text COLLATE pg_catalog."default",
    approved_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bus_bookings_pkey PRIMARY KEY (id),
    CONSTRAINT fk_bus_booking_user FOREIGN KEY (booked_by)
        REFERENCES public."User" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_bus_booking_bus FOREIGN KEY (bus_id)
        REFERENCES public.buss (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT chk_bus_booking_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_bus_booking_passengers CHECK (passenger_count IS NULL OR passenger_count > 0),
    CONSTRAINT chk_bus_booking_period CHECK (booking_period::text = ANY (ARRAY['MORNING'::character varying, 'SECOND_HALF'::character varying, 'FULL_DAY'::character varying, 'CUSTOM'::character varying]::text[])),
    CONSTRAINT chk_bus_booking_status CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying]::text[])),
    CONSTRAINT chk_bus_booking_time CHECK (end_date > start_date OR end_time > start_time)
)

TABLESPACE pg_default;