CREATE TABLE IF NOT EXISTS public.coordinators
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    employee_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Teaching'::text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT coordinators_pkey PRIMARY KEY (id),
    CONSTRAINT coordinators_employee_type_check CHECK (employee_type = ANY (ARRAY['Teaching'::text, 'Non-Teaching'::text, 'Both'::text, ''::text]))
)

TABLESPACE pg_default;
