CREATE TABLE IF NOT EXISTS public.dept_stationary_indents
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),

    department_id TEXT NOT NULL,
    reason VARCHAR(255),
    status VARCHAR(64),

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT dept_stationary_indents_pkey PRIMARY KEY (id),

    CONSTRAINT fk_department_id
        FOREIGN KEY (department_id)
        REFERENCES public."User" (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;
