CREATE TABLE IF NOT EXISTS public.stationary_indent_and_grants
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),

    dept_stationary_indent_id BIGINT NOT NULL,

    stationary_id BIGINT NOT NULL,

    request_quantity INTEGER NOT NULL
        CHECK (request_quantity > 0),

    request_date DATE NOT NULL,

    grant_quantity INTEGER NOT NULL DEFAULT 0
        CHECK (grant_quantity >= 0),

    grant_date DATE,

    created_at TIMESTAMP,
    updated_at TIMESTAMP,

    CONSTRAINT stationary_indent_and_grants_pkey PRIMARY KEY (id),

    CONSTRAINT fk_indent
        FOREIGN KEY (dept_stationary_indent_id)
        REFERENCES public.dept_stationary_indents (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,

    CONSTRAINT fk_stationary
        FOREIGN KEY (stationary_id)
        REFERENCES public.stationaries (id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;
