CREATE TABLE hall_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    hall_id BIGINT NOT NULL,
    booked_by TEXT NOT NULL,

    purpose VARCHAR(255),
    start_datetime TIMESTAMP NOT NULL,
    end_datetime TIMESTAMP NOT NULL,

    -- status VARCHAR(20) DEFAULT 'PENDING',
    remarks TEXT,

    approved_by TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_hall
        FOREIGN KEY (hall_id)
        REFERENCES halls(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_approved_by
        FOREIGN KEY (approved_by)
        REFERENCES "User"(id)
        ON DELETE SET NULL,

    CONSTRAINT chk_booking_time
        CHECK (end_datetime > start_datetime)
)
TABLESPACE pg_default;