CREATE TABLE IF NOT EXISTS public.vehicle_bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vehicle_id BIGINT NOT NULL,
    booked_by TEXT NOT NULL,
    booked_by_email TEXT,

    purpose VARCHAR(255),
    destination VARCHAR(255),

    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    booking_period VARCHAR(20) NOT NULL DEFAULT 'FULL_DAY',

    start_time TIME NOT NULL,
    end_time TIME NOT NULL,

    passenger_count INTEGER,

    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    remarks TEXT,

    approved_by TEXT,
    approved_at TIMESTAMP,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vehicle_booking_vehicle
        FOREIGN KEY (vehicle_id)
        REFERENCES public.vehicles(id),

    CONSTRAINT fk_vehicle_booking_user
        FOREIGN KEY (booked_by)
        REFERENCES public."User"(id),

    CONSTRAINT chk_vehicle_booking_period
        CHECK (
            booking_period IN (
                'MORNING',
                'SECOND_HALF',
                'FULL_DAY',
                'CUSTOM'
            )
        ),

    CONSTRAINT chk_vehicle_booking_dates
        CHECK (
            end_date >= start_date
        ),

    CONSTRAINT chk_vehicle_booking_time
        CHECK (
            end_date > start_date
            OR end_time > start_time
        ),

    CONSTRAINT chk_vehicle_booking_passengers
        CHECK (
            passenger_count IS NULL
            OR passenger_count > 0
        ),

    CONSTRAINT chk_vehicle_booking_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELLED'
            )
        )
)
TABLESPACE pg_default;