CREATE TABLE vehicle_bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    booked_by TEXT NOT NULL,
    purpose VARCHAR(255),
    destination VARCHAR(255),
    travel_date DATE NOT NULL,
    start_time TIME,
    expected_return_time TIME,
    passenger_count INTEGER,
    status VARCHAR(20) DEFAULT 'PENDING',
    remarks TEXT,
    -- approved_by TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_vehicle
        FOREIGN KEY (vehicle_id)
        REFERENCES vehicles(id),

    CONSTRAINT fk_user_vehicle
        FOREIGN KEY (booked_by)
        REFERENCES "User"(id)
)TABLESPACE pg_default;