CREATE TABLE IF NOT EXISTS public.faculty_book_indent_forms
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),

    requested_by text COLLATE pg_catalog."default" NOT NULL,
    requested_by_email text COLLATE pg_catalog."default" NOT NULL,
    faculty_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    library_id_no character varying(50) COLLATE pg_catalog."default" NOT NULL,

    branch_id integer,

    books_required_for character varying(50) COLLATE pg_catalog."default" NOT NULL,
    semester character varying(20) COLLATE pg_catalog."default" NOT NULL,

    book_author character varying(255) COLLATE pg_catalog."default" NOT NULL,
    book_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    publisher character varying(255) COLLATE pg_catalog."default" NOT NULL,
    required_quantity integer NOT NULL,
    student_strength integer NOT NULL,
    book_type character varying(20) COLLATE pg_catalog."default" NOT NULL,
    remarks text COLLATE pg_catalog."default",

    status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Pending'::character varying,

    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT faculty_book_indent_forms_pkey PRIMARY KEY (id),

    CONSTRAINT fk_fbif_requested_by FOREIGN KEY (requested_by)
        REFERENCES public."User" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,

    CONSTRAINT fk_fbif_branch FOREIGN KEY (branch_id)
        REFERENCES public.branches (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL,

    CONSTRAINT chk_fbif_quantity CHECK (required_quantity > 0),
    CONSTRAINT chk_fbif_student_strength CHECK (student_strength > 0),

    CONSTRAINT chk_fbif_books_required_for CHECK (books_required_for::text = ANY (ARRAY[
        'UG'::character varying,
        'PG'::character varying,
        'Doctoral'::character varying,
        'Common to all/General Reading'::character varying
    ]::text[])),

    CONSTRAINT chk_fbif_semester CHECK (semester::text = ANY (ARRAY[
        '1st'::character varying,
        '2nd'::character varying,
        '3rd'::character varying,
        '5th'::character varying,
        '6th'::character varying,
        '7th'::character varying,
        '8th'::character varying,
        'Common to all'::character varying
    ]::text[])),

    CONSTRAINT chk_fbif_book_type CHECK (book_type::text = ANY (ARRAY[
        'Reference'::character varying,
        'Textbook'::character varying,
        'General'::character varying
    ]::text[])),

    CONSTRAINT chk_fbif_status CHECK (status::text = ANY (ARRAY[
        'Pending'::character varying,
        'Approved'::character varying,
        'Ordered'::character varying,
        'Received'::character varying,
        'Rejected'::character varying
    ]::text[]))
)

TABLESPACE pg_default;
